name: Validate Windows Servers

on:
  schedule:
    - cron: "0 6 * * *" # Runs daily at 6 AM UTC
  workflow_dispatch: # Manual trigger

jobs:
  validate-servers:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run PowerShell Script
        shell: pwsh
        run: |
          $scriptPath = "$env:GITHUB_WORKSPACE/scripts/validate_rdp.ps1"
          $serverList = "$env:GITHUB_WORKSPACE/servers.txt"
          $outputCsv = "$env:GITHUB_WORKSPACE/RDP_Report.csv"
          $username = "${{ secrets.ADMIN_USERNAME }}"
          $password = "${{ secrets.ADMIN_PASSWORD }}"

          # Execute the script
          & $scriptPath -ServerListPath $serverList -OutputCsvPath $outputCsv -Username $username -Password $password

      - name: Send Email with Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "RDP Server Validation Report"
          body: "Attached is the latest RDP validation report."
          to: recipient@example.com
          from: "GitHub Actions <noreply@example.com>"
          attachments: "RDP_Report.csv"